### ISSUE TITLE
Is this operator still under development and being maintained?

### ISSUE THREAD

**Issue by callum-stakater** [noseka1/gitops-friendly-machinesets-operator#1]
There is a ref to use this operator in https://access.redhat.com/solutions/6831811 but it doesnt appear to be maintained or?

**Comment by noseka1** [comment]
The operator should work as documented. If it is not the case, you can file a bug report. Patches and improvements are accepted.

**Comment by noseka1** [comment]
I tested the operator on OpenShift 4.13.6 just now. It works as expected.
